<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Lei Huang</title>

	<link rel="stylesheet" href="style.css">
</head>
<body>
    <h1>Project Euler</h1>
	<h2>Problem 2: Even Fibonacci Numbers</h2>
	<p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:<br><br>

	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...<br><br>

	By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>

<?php

function addEvenFibonacciNumbers(){

	$fibonacci = array(
		1,
		2
	);

	$current_num = $fibonacci[1];
	$previous_num = $fibonacci[0];
	$sum = $fibonacci[1];

	do{
		$next_num = $current_num + $previous_num;

		if ($next_num % 2 == 0){
			$sum += $next_num;
		}

		$previous_num = $current_num;
		$current_num = $next_num;

	} while ($next_num <= 4000000);

	return $sum;

}

echo "The sum of all even Fibonacci numbers whose values do not exceed 4 million is ", addEvenFibonacciNumbers();

?>
</body>
</html>
